apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  labels: {{ include "app.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "app.selector" . | indent 6 }}
  template:
    metadata:
      labels: {{ include "app.labels" . | indent 8 }}
      annotations:
      {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          #command: [ "/bin/sh", "-c", "env" ]
          env:
            - name: LDAP_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: ldap-server
                  key: ldap.serverurl
            - name: LDAP_BASE_DN
              valueFrom:
                configMapKeyRef:
                  name: ldap-server
                  key: ldap.basedn
            - name: LDAP_LOGIN_DN
              valueFrom:
                configMapKeyRef:
                  name: ldap-server
                  key: ldap.logindn
            - name: LDAP_SERVER_ADMIN_PWD #change to secret
              valueFrom:
                configMapKeyRef:
                  name: ldap-server
                  key: ldap.adminpwd
